### ISSUE TITLE
Version error in server/common.cpp on the server side at proto2 branch

### ISSUE THREAD

**Issue by TeapoyY** [huailiang/game_socket_protobuf#1]
The version of protobuff defined in the server side is `3001000`, which is `3.1` I suppose and it is not compatible with the `3.5.1`.
I replaced the whole `google/protobuff` folder with `3.5.1` version protobuff and finally got it working.
I wonder whether this is an problem with the uploaded files or I am doing something wrong.

:)

**Comment by TeapoyYinYue** [comment]
Forgot to mention that in the scene "socket", the script associated with the student button does not give the `Name` of the `Student` message, which will cause the server to crash as the `Name` field is a required field.

This is also on the proto2(client_protobuf_v2) branch.
